# Generated by Django 2.1.15 on 2023-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor_Banco',
            fields=[
                ('GESTOR_BANCO', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Codigo_Banco', models.CharField(max_length=255)),
                ('Descricao', models.TextField()),
            ],
            options={
                'db_table': 'GESTOR_BANCO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido_Materiais',
            fields=[
                ('PEDIDO', models.IntegerField(primary_key=True, serialize=False)),
                ('EMPRESA', models.IntegerField()),
                ('COTACAO', models.IntegerField()),
                ('DATA', models.DateTimeField()),
                ('DTFECHAMENTO', models.DateTimeField()),
                ('DTENTREGA', models.DateTimeField()),
                ('FORNECEDOR', models.IntegerField()),
                ('CLIENTE', models.IntegerField()),
                ('TIPO', models.CharField(max_length=15)),
                ('CENTRO_CUSTO', models.IntegerField()),
                ('SETOR', models.IntegerField()),
                ('CATEG', models.CharField(max_length=5)),
                ('CLASS', models.CharField(max_length=5)),
                ('CLASSE', models.IntegerField()),
                ('TPCOMPRA', models.IntegerField()),
                ('FPGTOID', models.IntegerField()),
                ('FPGTO', models.CharField(max_length=30)),
                ('PRAZO_ENTREGA', models.CharField(max_length=30)),
                ('VENDEDOR_ID', models.IntegerField()),
                ('VENDEDOR', models.CharField(max_length=30)),
                ('AOSCUIDADOS', models.CharField(max_length=30)),
                ('SEUPEDIDO', models.CharField(max_length=30)),
                ('QUANT_ITENS', models.FloatField()),
                ('VLRFRETE', models.FloatField()),
                ('TOTAL_PRODUTOS', models.FloatField()),
                ('TOTAL_PRODUTOS_IPI', models.FloatField()),
                ('TOTAL_SUBSTITUICAO', models.FloatField()),
                ('TOTAL_PEDIDO', models.FloatField()),
                ('URGENCIA', models.CharField(max_length=10)),
                ('NF', models.IntegerField()),
                ('POSICAO', models.CharField(max_length=15)),
                ('POSICAOENT', models.CharField(max_length=15)),
                ('POSICAOESPERA', models.CharField(max_length=15)),
                ('OBS', models.TextField()),
                ('PA', models.IntegerField()),
                ('STATUS', models.CharField(max_length=30)),
                ('PCP', models.IntegerField()),
                ('APROVACAO', models.IntegerField()),
                ('FIN', models.CharField(max_length=2)),
                ('PAFIN', models.IntegerField()),
            ],
            options={
                'db_table': 'PEDIDO_MATERIAIS',
                'managed': False,
            },
        ),
    ]
